language: php

php:
  - 7.2

sudo: required

dist: xenial

addons:
  apt:
    packages:
      - libgconf-2-4
    update: true

install:
  - travis_retry composer install --no-interaction --prefer-dist
  - yarn install

script:
  - npx cypress run
  - vendor/bin/phpstan analyse -l max src/
